### ISSUE TITLE
OSC - Allow changing the inbound traffic IP

### ISSUE THREAD

**Issue by guyfawcus** [JupiterBroadcasting/CasterSoundboard#35]
More often than not (for myself at least), the thing sending the OSC messages is on the same computer.

I'm not saying that it should be the default, but this should at least be configurable.

Say for example the traffic is coming from localhost (127.0.0.1) or a different NIC...

I hacked this up to be able to test #33 out by setting the [read-only](https://github.com/JupiterBroadcasting/CasterSoundboard/blob/ee5cd71f603b7ec609aa7d6fa620e460166bc6fd/CasterSoundboard/CasterOSCServerConfigPicker.cpp#L43) flag on the input box to false and using `setValidator` on it but I know it's not how it should be done so I'll leave it to someone who know what they're doing to submit a PR 😉.

**Comment by covarianttensor** [comment]
That's isn't necessary. The server is listening  on IP 0.0.0.0, which means it will accept connections from anywhere. The IP address shown is just so that people using an app like TouchOSC know where to point it to over a network. Sending messages over localhost (127.0.0.1) should still work. If you look at the source code closely, you will see that even you I where to disable read only on the textbox and change the IP, the the server doesn't even return the IP written in the dialog box, or is used at all. What you will see is `QHostAddress::Any` which accepts all connections on IPv4 and IPv6.

**Comment by guyfawcus** [comment]
Very true! No idea how I managed to miss that, likely because I'm just used to sending/receiving unicast massages rather than multicast. Probably typed the port number wrong or something and attributed the failure to the wrong thing. Cheers for clearing that up and especially for pointing out how the code actually works, it's much appreciated 👍
