### ISSUE TITLE
Build issue notifications

### ISSUE THREAD

**Issue by guyfawcus** [JupiterBroadcasting/CasterSoundboard#51]
This issue is just being used to notify a few authors to some small bugs/ideas.

- [x] Since 1d6c7db6de515a452a33fd4c3b26d2d2c13a1eb2 the snap package is [failing to build](https://build.snapcraft.io/user/JupiterBroadcasting/CasterSoundboard/), pretty sure this is becasue it was moved `snap/snapcraft.yaml → dist/snap/snapcraft.yaml` - @rikai, do you need to change the location that the builder points to?
- [x] The [copr build service](https://copr.fedorainfracloud.org/coprs/fszymanski/castersoundboard/package/castersoundboard/) doesn't seem to be updating - @fszymanski, do you need to enable automatic building, have a hook set up for you or are you just planning on releasing manually?
- [x] Now that all of the distro files have been moved under [dist](https://github.com/JupiterBroadcasting/CasterSoundboard/tree/master/dist) - @aszlig, could [default.nix](https://github.com/JupiterBroadcasting/CasterSoundboard/blob/f4e59f85a8aba63476819c69122ffdab69a8a8bc/default.nix) also be moved under that directory without any problems? Perhaps under a `nix` specific folder like `dist/nix/default.nix`

**Comment by ghost** [comment]
1) You're probably right.
2) The GitHub webhook is not set up. I think about it and for the time being I build manually.
3) We could do that.

**Comment by rikai** [comment]
Regarding the snap, i've already spoken with @flexiondotorg and he will be fixing that as soon as he has the time. He's much more familiar with snaps than i am. 👍

**Comment by guyfawcus** [comment]
Good stuff! Cheers 👌

**Comment by aszlig** [comment]
@maelstrom59: The default.nix can be relocated, only the path in the `src` attribute needs to be changed to `../../CasterSoundboard` then.

The reason this is usually in the top-level directory is because you can easily build this with just `nix-build` or even just `nix-build https://github.com/JupiterBroadcasting/CasterSoundboard/archive/master.tar.gz` without a clone whereas now it's `nix-build dist/nix` or `nix-shell dist/nix`.

Hm, but this reminds me that it would probably also make sense to add a release.nix to the dist/nix dir, so we could build all sorts of packages, like debs, rpms, docker images or even windows/osx builds.

**Comment by guyfawcus** [comment]
Looks like @flexiondotorg moved the snap back out in 375cfcef8d923e562dde40ebc4006fc940a160fc so `default.nix` isn't alone now 😏.

Your reason for keeping it in the root dir is a good one, I'm certainly lazy enough to appreciate that sort of thing! I would say that if you have more Nix related stuff in mind, it'd probably be better to keep it under a sub-directory though. I'll leave it to you 👍 

P.S. I've gotta check out [NixOS](https://nixos.org/) now! I heard about it in a video about reproducible builds ([think it was this one](https://www.youtube.com/watch?v=ooJXRBf72M0)) a little while ago, now it's really piqued my interest.

**Comment by guyfawcus** [comment]
Thanks all for your input!
